### ISSUE TITLE
When porting other packages to python3, gslrandom breaks when importing `multinomial_par`

### ISSUE THREAD

**Issue by mpacer** [slinderman/gslrandom#4]
Hi,

I've been running into a series of issues while trying to port [`pyhawkes`](https://github.com/slinderman/pyhawkes) to be able to work with `python3`. In particular the problem that I'm running into with this package is that when I attempt to run one of the demos, it stalls on importing functions from this package, specifically `multinomial_par`

Here's the error code:

```
File "examples/continuous_demo.py", line 11, in <module>
import pyhawkes.models
File …/pyhawkes/models.py", line 18, in <module> 
from pyhawkes.internals.parents import DiscreteTimeParents
File …/pyhawkes/internals/parents.py", line 5, in <module> 
from gslrandom import multinomial_par, multinomial
ImportError: cannot import name 'multinomial_par'
```

My guess is that this has something to do with how gslrandom installs metaclass objects that are given relative paths rather than absolute paths, I don't entirely understand what that means though nor how to fix it, especially since this package proves somewhat difficult to build in the first place (since it requires compiling with clang-omp) and I could believe that some of this metaclass work might be being done in C elsewhere for the purposes of optimization.

**Comment by slinderman** [comment]
Thanks Michael, and sorry that I didn't see this issue earlier. I think there are two things going on here: 1) I messed up the Python3 relative imports, and 2) We recently switched to a new interface that just uses `multinomial`. That function will determine whether or not to use openmp under the hood. 

For 1), I just checked in a fix that will hopefully play nicely with Python 3. See https://github.com/slinderman/gslrandom/commit/958974dfc7eb6a6819a90fc09afd09d93e8bf04b
For 2) I've updated PyHawkes accordingly.

If you're still working on this, can you reopen if you have any more issues?

**Comment by mpacer** [comment]
HI Scott — no worries about not seeing it right away. I won't be able to
work with this for a while because I'm trying to finish up some stuff using
my graph based framework for a slightly different (but related) set of
problems. But once I have that in place, I'll look at this again and will
let you know if I run into any new issues.
