### ISSUE TITLE
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]

### ISSUE THREAD

**Issue by skwirut** [slinderman/gslrandom#5]
Getting this error trying to install gslrandom with pip.

  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  creating build/lib.linux-x86_64-2.7/gslrandom
  copying gslrandom/__init__.py -> build/lib.linux-x86_64-2.7/gslrandom
  running build_ext
  building 'gslrandom.gslrandom' extension
  creating build/temp.linux-x86_64-2.7
  creating build/temp.linux-x86_64-2.7/gslrandom
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/local/include -Igslrandom/ -I/home/local/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/local/anaconda2/include/python2.7 -c gslrandom/gslrandom.cpp -o build/temp.linux-x86_64-2.7/gslrandom/gslrandom.o -O3 -w -std=c++11 -fopenmp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  In file included from gslrandom/gslrandom.cpp:327:0:
  gslrandom/cgslrandom.h:1:25: fatal error: gsl/gsl_rng.h: No such file or directory
   #include <gsl/gsl_rng.h>
                           ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

**Comment by skwirut** [comment]
This was CentOS

Doing sudo yum install gsl-devel fixed it.

**Comment by slinderman** [comment]
Thanks for clarifying this! Yes, GSL is a dependency; specifically, you
need the headers that come in the gsl-devel package on linux.
